### ISSUE TITLE
chainChanged emits on page load

### ISSUE THREAD

**Issue by mqklin** [MetaMask/providers#110]
**Describe the bug**
Sometimes `chainChanged` message emits on every page load. So if I have this line in my code: `ethereum.on('chainChanged', (_chainId) => window.location.reload());` then user gets endless page refresh loop.

**To Reproduce**
I couldn't reproduce this, but one of our user shared his screen and I saw this endless page refresh loop. I added `  console.log('chainChanged');` to that event callback, and console showed this log every time before page refreshed.

**Expected behavior**
`chainChanged` event should be sent only on chain change, not on page load

**Browser details**
 - OS: OS X
 - Browser: last Chrome
 - MetaMask Version: 8.0.8

**Comment by zimmah** [comment]
Since which version is this fixed? Because I'm still having this issue. (not sure if I have the latest version, BTW I use the build-in wallet by brave that's based on metamask)

**Comment by rekmarks** [comment]
We haven't shipped this yet due to the holidays, but it will be included in version 9 of the MetaMask extension.

_Edit:_ Expect it early in the New Year.

**Comment by mqklin** [comment]
> The localStorage solution above runs somewhat slowly because of the call to getChainId, slower than the pretty fast timer on producing this warning:

@wbt I moved `window.ethereum.autoRefreshOnNetworkChange = false;` line **before** `async` function and don't see it anymore.

**Comment by laygir** [comment]
I'm having this issue with Brave but not with Chrome.

Brave v1.34.81 Chromium: 97.0.4692.99
MetaMask v10.8.1

**Comment by Sheriik** [comment]
Having this issue on android with TrustWallet browser.
