### ISSUE TITLE
Incorporate backwards-compat with pre-v9 MetaMask

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/providers#137]
Maskbook has needed to [import a custom version of this inpage provider](https://github.com/DimensionDev/Maskbook/blob/eb06efa907bb0a64999be83a45002bac94309753/packages/maskbook/src/extension/background-script/EthereumServices/providers/MetaMask.ts) in order to [conditionally fall back to an older version](https://github.com/DimensionDev/extension-provider/blob/master/index.js) for older MetaMask users.

This issue is probably caused because we changed the name of our inter-process stream from `provider` to `metamask-provider`.

We should probably preserve the backwards-compat of this library if possible.

**Comment by Gudahtt** [comment]
I don't think this is something we should attempt. The changes we'd require for this are _vast_ (e.g. we'd need to re-implement all of the old streams replaced [here](https://github.com/MetaMask/inpage-provider/pull/109) while keeping the new ones), and it would benefit almost nobody.

We are forced to maintain compatibility with older inpage providers in the extension for a certain period to ensure sites with embedded providers have the opportunity to update. So anybody using an embedded provider can wait until all of their users are on the new MetaMask version before updating. Making the provider backwards-compatible with pre-v9 MetaMask wouldn't help anyone using this library maintain compatibility.

The _only_ advantage to doing this would be to preserve indefinite compatibility (i.e. well beyond the rollout period) between sites/extensions using an embedded provider and users with outdated MetaMask extensions (i.g. MetaMask users who have updates disabled and users of MetaMask forks). Even for those users, dapps/extensions could support them by instantiating multiple providers if they'd like. I don't think it's worth the added time or complexity to support compatibility between the tiny fraction of users with updates disabled and the tiny fraction of sites/extensions embedding a provider.

In general I think we should do everything we can to avoid changing how the inpage provider communicates with the extension, to avoid these issues of compatibility altogether. But if we're going to make these changes (which we have), the best way to ensure nothing breaks is to build backwards compatibility into the extension. We did that for embedded providers (see the `LegacyProvider` comments scattered throughout the extension), but we forgot to do this for extension providers. We can fix the extension provider situation either in the extension or in `metamask-extension-provider`, but I don't think it should be addressed here.

**Comment by danfinlay** [comment]
I think that’s a strong case, and since the only possible consumer has implemented the workaround and it’d be more work just for them to move off it, I think we can close this.
