### ISSUE TITLE
Events don't work

### ISSUE THREAD

**Issue by nugaon** [MetaMask/providers#15]
I use the inpage-provider with the "extension-port-stream" package at my extension's index page.
The application with the provider can't get subscription events (for example at newBlockHeaders, or receive transaction receipts after send).
```javascript
this.web3.client.eth.subscribe('newBlockHeaders', (error, result) => {
      if (error) {
        console.error("Error happened at new block", error);
        return;
      }
    })
    .on("data", function(blockHeader){
      console.log("blockHeader", blockHeader);
    });
```
It shows some errors because of wallet_sendDomainMetadata, unexcepted account change
 and also the eventemitter memory leak, but the provider also seems initialized correct way, also I can send transactions, etc.
![Screenshot from 2020-02-06 19-01-25](https://user-images.githubusercontent.com/50576770/73964896-696a4580-4913-11ea-9530-6aecbd0c964c.png)
![Screenshot from 2020-02-06 17-46-03](https://user-images.githubusercontent.com/50576770/73960341-feb50c00-490a-11ea-8ab4-86333791cd73.png)
![Screenshot from 2020-02-06 17-46-14](https://user-images.githubusercontent.com/50576770/73961296-9bc47480-490c-11ea-8d5e-8f8e4b827903.png)

Init process:
```javascript
    const metamaskPort = chrome.runtime.connect("nkbihfbeogaeaoehlefnkodbefgpgknn");
    const pluginStream = new PortStream(metamaskPort);
    let provider = new MetamaskInpageProvider(pluginStream);
    console.log("provider", provider);
    this.web3.client = new Web3(provider);
```

version: 4.0.4 (npm)
web3: 1.2.6
browser: Chrome 80.0.3987.87

**Comment by nugaon** [comment]
I checked what comes from the chrome's Port object directly for event subscriptions, and the events are fires correctly, just my listener functions aren't called on those. Also that I noticed the 'once' methods on send methods don't work very well, because after the first event it doesn't close the subscription and the Port object sends the events further.

**Comment by rekmarks** [comment]
Hi @nugaon, thank you for opening an issue. We're looking into this and will get back to you this week.

**Comment by nugaon** [comment]
For the EventEmitter memory leak problem, the main metamask extension deals with this one line code: https://github.com/MetaMask/metamask-extension/blob/c0d6121cd9c037cf46bbd3af85477172507614da/app/scripts/inpage.js#L62

So it is handled outside from this repo originally, but the current examples don't append this line for using the metamask-inpgage-provider.

**Comment by rekmarks** [comment]
Hello @nugaon, I apologize it's taken me so long to get back to you on this.

I believe some of the issues you described should be alleviated now. Have you checked recently?

What version of `web3` are you using?

**Comment by nugaon** [comment]
Hi @rekmarks, I use 1.2.6 version of web3. I checked recently maybe this would be the problem and as I see in the main repo's package.json, the Metamask uses ^0.20.7 which is a significant version difference. Is there any plan recently to update its version?
At the new version there is no sendAsync function already, only the normal send methods with the EventEmitter returns that I also use in my application. As I see this repo doesn't support this way to handle send requests only the sendAsync functions yet.
If you would like to redesign and update it I would love to help in this, if somehow we could get in touch, because I don't know the roadmap of the development as you can see at #20 pull request too.

**Comment by rekmarks** [comment]
Hm. Can you message me on Telegram? Same handle as GitHub.

**Comment by nugaon** [comment]
Hey @rekmarks I left you a message then on Telegram.

**Comment by rekmarks** [comment]
Discussion taken elsewhere.
