### ISSUE TITLE
MetaMask: 'eth_accounts' unexpectedly updated accounts

### ISSUE THREAD

**Issue by wjmelements** [MetaMask/providers#16]
Reporting as requested.

I first noticed the issue after merging develop in https://github.com/MetaMask/metamask-extension/pull/7987#issuecomment-583123624 so I suspect the issue is caused in this patch https://github.com/MetaMask/metamask-extension/pull/7997 .

I reproduce the issue on develop by signing in to metamask, visiting https://ratifier.trusttoken.com and adding that site to "Connected Sites". It shows in the console for the page.

**Comment by rekmarks** [comment]
Thank you @wjmelements for reporting this.

After testing on the website you listed, I was able to determine that this was incorrectly interpreted as an error, and a condition will be added to prevent it from happening again. `4.1.1` of this module will contain a fix.
