### ISSUE TITLE
Fix `.d.ts` extension usage in type declaration exports

### ISSUE THREAD

**Issue by MajorLift** [MetaMask/providers#335]
We should set up `ts-bridge` to generate and expose unambiguous `.d.cts` and `.d.mts` type declarations only. 

Using `.d.ts` causes issues in downstream projects that have their `moduleResolution` option set to `Node16` or `NodeNext`.

e.g. 
```ts
error TS2307: Cannot find module '@metamask/providers' or its corresponding type declarations.
```
> https://github.com/MetaMask/core/actions/runs/9668650800/job/26673339021?pr=3645

**Comment by mcmire** [comment]
@MajorLift I believe that this is one of the design goals of `ts-bridge` and so it does this by default. If you view the latest version of `@metamask/utils` you can see separate `.d.cts` and `.d.mts` files: https://npmfs.com/package/@metamask/utils/8.5.0/dist/
